### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by hauntsaninja** [L3viathan/batchable#1]
Neat idea! You may also be interested in https://github.com/quora/asynq

Also there's a small typo in the README, should `def shop_lookup` be `def lookup_shop`?

**Comment by L3viathan** [comment]
Fixed the typo, thanks!

I wasn't aware of `asynq`, but from the README it looks like I would need to already know all the aids (shop or brand IDs in our examples) beforehand, whereafter it would help with batching the requests.

In this project, you write code that looks completely unbatched (other than the decorators). Or how would I write the `transform_offer` function using `asynq`?
